jobs:
  include:
    - name: "Python 3.8.0 on Bionic Linux"
      dist: bionic
      python: 3.8
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell

before_install:
 - pip install --only-binary=all cython numpy coveralls
install:
 - python setup.py install
script:
 - python setup.py test
 - python -m coverage run --source=./bgen -m unittest discover
after_success:
 - coveralls
