language: python

env:
  global:
    - CIBW_SKIP="cp27-* cp35-* pp*"
    - CIBW_TEST_COMMAND="python -m unittest discover -s {project}"
    - TWINE_USERNAME=__token__

jobs:
  include:
    - services: docker
      env:
        - CIBW_BEFORE_BUILD="yum install -y zlib-devel"

before_install:
 - pip3 install --only-binary=all cython cibuildwheel==1.4.2
 - python3 setup.py sdist
script:
 - python3 setup.py test
 - cibuildwheel --output-dir wheelhouse
after_success:
 - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload --skip-existing wheelhouse/*.whl
      python3 -m twine upload --skip-existing dist/*.tar.gz
    fi
